
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-04
owner: ucsb-cs156-f25
repo_name: team01-f25-04
pull_requests: [{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-create-controller","number":50,"title":"ap-created HelpRequestController and added GET&POST mappings","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/50"},{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-MenuItemReview-Database-Table","number":47,"title":"ca - create database table for MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/47"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"xy-UCSBDiningCommonsMenuItem-create-db","number":46,"title":"pc - create database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/46"}]
