
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-04
owner: ucsb-cs156-f25
repo_name: team01-f25-04
pull_requests: [{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-MenuItemReview-delete-request","number":76,"title":"Ca - delete request for Menu Item Review","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/76"},{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-MenuItemReview-PUT","number":75,"title":"Ca - menu item review PUT request for Menu Item Review","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/75"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"pc-menuitem-delete","number":65,"title":"Delete function for UCSBDiningCommonsMenuItems Table","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/65"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"pc-menuitems-put","number":64,"title":"Put/Edit for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/64"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"pc-menuitems-get-by-id","number":63,"title":"GetByID Addition UCSBDiningCommonsMenuItem table","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/63"}]
