
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-04
owner: ucsb-cs156-f25
repo_name: team01-f25-04
pull_requests: [{"author":{"id":"U_kgDOCQ1dXg","is_bot":false,"login":"Max-Changg","name":"Max Chang"},"headRefName":"RecommendationRequest-create-db","number":54,"title":"Recommendation request create db","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/54"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-add-delete","number":53,"title":"ap - Added DELETE endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/53"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-add-put","number":52,"title":"ap - Added PUT (edit) endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/52"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-add-get","number":51,"title":"ap - Added GET (show) endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/51"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-HelpRequest-create-controller","number":50,"title":"ap-created HelpRequestController and added GET (index) & POST (create) mappings","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/50"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"xy-UCSBDiningCommonsMenuItem-create-db","number":46,"title":"pc - create database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/46"}]
