
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-04
owner: ucsb-cs156-f25
repo_name: team01-f25-04
pull_requests: [{"author":{"id":"MDQ6VXNlcjIzNTY0NDU2","is_bot":false,"login":"RyanHung","name":"Ryan Hung"},"headRefName":"rh-add-DELETE-articles-db","number":77,"title":"Rh add delete articles db","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/77"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"pc-menuitem-delete","number":65,"title":"Delete function for UCSBDiningCommonsMenuItems Table","url":"https://github.com/ucsb-cs156-f25/team01-f25-04/pull/65"}]
